--- #YAML:1.0
name:               WebDyne
version:            1.210
abstract:           create web pages with embedded Perl
author:
    - Andrew Speer <andrew@webdyne.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:                0
    Digest::MD5:        0
    Env::Path:          0
    HTML::Tagset:       0
    HTML::TreeBuilder:  0
    HTTP::Status:       0
    Storable:           0
    Text::Template:     0
    Tie::IxHash:        0
resources:
    homepage:  http://webdyne.org
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
