---
abstract: 'create web pages with embedded Perl'
author:
  - 'Andrew Speer <andrew@webdyne.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120351'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebDyne
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 0
  Digest::MD5: 0
  Env::Path: 0
  HTML::Tagset: 0
  HTML::TreeBuilder: 0
  HTTP::Status: 0
  Storable: 0
  Text::Template: 0
  Tie::IxHash: 0
resources:
  homepage: http://webdyne.org
  license: http://www.gnu.org/licenses/gpl.html
version: 1.225
